export const metadata = {
  title: 'Internship Portal',
  description: 'Generated by create next app',
};

const cardData = [
  {
    title: 'Find Your Perfect Internship',
    description: 'Explore various internship opportunities suited for your skills and interests.',
  },
  {
    title: 'Apply Seamlessly',
    description: 'Apply directly to your desired internships with just a few clicks.',
  },
  // Add more card data as needed
];

export default function Home() {
  return (
    <div className='flex flex-col items-center justify-center'>
      <h1 className='text-5xl mb-8'>Welcome to Internship Portal</h1>
      <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6'>
        {cardData.map((card, index) => (
          <div
            key={index}
            className='bg-white rounded-lg p-6 shadow-md hover:shadow-lg transition duration-300 ease-in-out'
          >
            <h2 className='text-xl font-semibold mb-4'>{card.title}</h2>
            <p>{card.description}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
