
import React from 'react'
import { Col, Row, Container, Card } from "react-bootstrap";
import CNavbar from './components/CNavbar';


function App() {
  return (
    <div>
      <CNavbar />
      <Container style={{marginTop: '100px', marginBottom: '100px'}}>
        <Row className="d-flex justify-content-center align-items-center">
          <Col md={8} lg={10} xs={12}>
          <div className="border border-2 border-primary"></div>
            <Card className="shadow px-4">
              <h1><br/><b>Internship Management Portal</b></h1>
              <h2>
                for Student & Teachers of KJSIT
                <br/><br/><br/>
              </h2>
              <h4>
                <b>Update:</b> Students can update their profiles with information about internships they have completed till now. This information can be then accessed by the teachers.
                <br/><br/>
              </h4>
              <h4>
                <b>Requests:</b> Students can submit requests to participate in internships and get approved by the respective teachers. The teachers can approve or decline these requests with a message remark.
                <br/><br/>
              </h4>
              <h4>
                <b>Download:</b> Upon receiving all approvals by respective teachers, students can download the proof of the approval as a pdf document generated by the website.
                <br/><br/>
              </h4>
              <h4>
                <b>Announcements:</b> Teachers can post announcements about internships and other opportunites for students to avail.
                <br/><br/>
              </h4>
              <h4>
                <b>Manage:</b> Teachers can search through the students in the database and view their information with blazing fast speeds.
                <br/><br/>
              </h4>
              {/* <p>
                Lorem ipsum dolor sit amet consectet
                <br/>
              </p> */}
              
              <p> made with ❤️</p>
            </Card>
          </Col>
        </Row>
      </Container>
    </div>
  );
}

export default App;
